MLFlow Tracking Server

In [6]:
import mlflow

In [7]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [8]:
mlflow.set_experiment("Check Local Host Connection")

with mlflow.start_run():
    mlflow.log_metric("test 1", 1)
    mlflow.log_metric("test 2", 2)
    


🏃 View run nebulous-perch-409 at: http://127.0.0.1:5000/#/experiments/263844703129493147/runs/fd9ecb2e9f324729baa996742f803e10
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/263844703129493147


<!-- First Project using MLFlow -->

In [9]:
import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import train_test_split
import mlflow
from mlflow.models import infer_signature

In [10]:
#Data set Loading
X,y = datasets.load_iris(return_X_y=True)


In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
#Data Split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

In [13]:
x_train

array([[5. , 2.3, 3.3, 1. ],
       [6.7, 3.1, 5.6, 2.4],
       [5.6, 2.8, 4.9, 2. ],
       [4.9, 2.5, 4.5, 1.7],
       [5. , 3.3, 1.4, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [4.9, 3. , 1.4, 0.2],
       [6. , 2.2, 5. , 1.5],
       [7.7, 2.8, 6.7, 2. ],
       [5.2, 3.4, 1.4, 0.2],
       [6.1, 3. , 4.6, 1.4],
       [4.8, 3. , 1.4, 0.1],
       [7.2, 3.6, 6.1, 2.5],
       [4.9, 3.1, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 2.8, 4.8, 1.4],
       [5.7, 3. , 4.2, 1.2],
       [6.1, 2.6, 5.6, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [6.3, 2.5, 5. , 1.9],
       [5.7, 2.5, 5. , 2. ],
       [6.6, 3. , 4.4, 1.4],
       [5.6, 3. , 4.1, 1.3],
       [5. , 3.5, 1.3, 0.3],
       [5.5, 2.6, 4.4, 1.2],
       [5. , 2. , 3.5, 1. ],
       [7.7, 2.6, 6.9, 2.3],
       [6.7, 3.3, 5.7, 2.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.7, 1.5],
       [4.6, 3

In [14]:
#Define Model Hyperparameters
params = {"penalty" : None, "solver" : "newton-cg", "max_iter" : 500, "multi_class" : "auto", "random_state" : 8888}

#Training Model on Hyperparameters
lr=LogisticRegression(**params)


In [15]:
lr.fit(x_train, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=500, multi_class='auto', penalty=None,
                   random_state=8888, solver='newton-cg')

In [16]:
ypred = lr.predict(x_test)
ypred

array([1, 1, 1, 1, 0, 2, 1, 2, 0, 2, 0, 1, 2, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 2, 2, 0, 2, 0, 0, 2])

In [17]:
accuracy = accuracy_score(y_test, ypred)

<!-- """Model signatures are REQUIRED for registering models in Databricks Unity Catalog.""" -->

In [18]:
#MLFlow Tracking
mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000")

#Create new MLFlow Experiment
mlflow.set_experiment("MLFLOW QuickStart")

#Start MLFlow Run
with mlflow.start_run():
    #Log the Hyperparameters
    mlflow.log_params(params)

    #Log Acuracy Score
    mlflow.log_metric("Accuracy_Score", accuracy)

    #Set A Tag
    mlflow.set_tag("Training info", "Basic LR Model For Iris Dataset ")

    #Infer Model Signiture
    signiture = infer_signature(x_train, lr.predict(x_train))

    #Log the Model
    model_info = mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="iris_model",
        signature=signiture,
        input_example=x_train,
        registered_model_name="tracking-quickstart"
    )

    # Model Signiture is cruicle to 

2025/07/09 09:24:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Registered model 'tracking-quickstart' already exists. Creating a new version of this model...
2025/07/09 09:24:07 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: tracking-quickstart, version 7


🏃 View run sincere-deer-920 at: http://127.0.0.1:5000/#/experiments/186174863104388394/runs/581887b30a7b4a4c9dad5128ee54a883
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186174863104388394


Created version '7' of model 'tracking-quickstart'.


<!-- #inferencing -->

In [19]:
serving_payload = """{
  "inputs": [
    [
      6.3,
      2.5,
      5,
      1.9
    ],
    [
      6.3,
      3.4,
      5.6,
      2.4
    ],
    [
      5.5,
      2.3,
      4,
      1.3
    ],
    [
      6.2,
      2.8,
      4.8,
      1.8
    ],
    [
      5,
      3.2,
      1.2,
      0.2
    ],
    [
      4.9,
      3.1,
      1.5,
      0.1
    ],
    [
      5.5,
      2.5,
      4,
      1.3
    ],
    [
      5.2,
      3.5,
      1.5,
      0.2
    ],
    [
      7.7,
      2.6,
      6.9,
      2.3
    ],
    [
      5,
      3.5,
      1.3,
      0.3
    ],
    [
      6.4,
      3.2,
      5.3,
      2.3
    ],
    [
      4.8,
      3,
      1.4,
      0.1
    ],
    [
      5.6,
      3,
      4.1,
      1.3
    ],
    [
      6.3,
      2.3,
      4.4,
      1.3
    ],
    [
      6.4,
      2.8,
      5.6,
      2.2
    ],
    [
      4.5,
      2.3,
      1.3,
      0.3
    ],
    [
      4.8,
      3,
      1.4,
      0.3
    ],
    [
      4.9,
      3.1,
      1.5,
      0.2
    ],
    [
      5.9,
      3,
      4.2,
      1.5
    ],
    [
      6.9,
      3.1,
      4.9,
      1.5
    ],
    [
      5.1,
      3.3,
      1.7,
      0.5
    ],
    [
      6.4,
      3.2,
      4.5,
      1.5
    ],
    [
      5.6,
      2.8,
      4.9,
      2
    ],
    [
      7.3,
      2.9,
      6.3,
      1.8
    ],
    [
      6.1,
      3,
      4.9,
      1.8
    ],
    [
      7.1,
      3,
      5.9,
      2.1
    ],
    [
      6.7,
      3.1,
      4.7,
      1.5
    ],
    [
      5.5,
      2.6,
      4.4,
      1.2
    ],
    [
      6.7,
      2.5,
      5.8,
      1.8
    ],
    [
      6.7,
      3.3,
      5.7,
      2.5
    ],
    [
      6.7,
      3.1,
      5.6,
      2.4
    ],
    [
      6.5,
      3,
      5.2,
      2
    ],
    [
      6.4,
      2.9,
      4.3,
      1.3
    ],
    [
      4.6,
      3.6,
      1,
      0.2
    ],
    [
      6.3,
      2.8,
      5.1,
      1.5
    ],
    [
      4.4,
      2.9,
      1.4,
      0.2
    ],
    [
      7,
      3.2,
      4.7,
      1.4
    ],
    [
      5.8,
      2.7,
      5.1,
      1.9
    ],
    [
      5.4,
      3.4,
      1.5,
      0.4
    ],
    [
      6.4,
      2.8,
      5.6,
      2.1
    ],
    [
      5.1,
      3.5,
      1.4,
      0.2
    ],
    [
      5.9,
      3,
      5.1,
      1.8
    ],
    [
      6.8,
      3,
      5.5,
      2.1
    ],
    [
      5.9,
      3.2,
      4.8,
      1.8
    ],
    [
      6.1,
      2.8,
      4,
      1.3
    ],
    [
      6.9,
      3.1,
      5.1,
      2.3
    ],
    [
      5,
      3.6,
      1.4,
      0.2
    ],
    [
      6,
      2.7,
      5.1,
      1.6
    ],
    [
      6.7,
      3,
      5,
      1.7
    ],
    [
      4.6,
      3.2,
      1.4,
      0.2
    ],
    [
      5.8,
      2.6,
      4,
      1.2
    ],
    [
      6.1,
      2.8,
      4.7,
      1.2
    ],
    [
      7.7,
      3,
      6.1,
      2.3
    ],
    [
      5.8,
      4,
      1.2,
      0.2
    ],
    [
      7.7,
      2.8,
      6.7,
      2
    ],
    [
      6.1,
      3,
      4.6,
      1.4
    ],
    [
      4.6,
      3.1,
      1.5,
      0.2
    ],
    [
      5,
      2.3,
      3.3,
      1
    ],
    [
      5.6,
      2.7,
      4.2,
      1.3
    ],
    [
      6.4,
      3.1,
      5.5,
      1.8
    ],
    [
      7.2,
      3.2,
      6,
      1.8
    ],
    [
      5.5,
      2.4,
      3.7,
      1
    ],
    [
      5.6,
      2.9,
      3.6,
      1.3
    ],
    [
      5.7,
      2.8,
      4.5,
      1.3
    ],
    [
      6.3,
      2.9,
      5.6,
      1.8
    ],
    [
      5.1,
      3.8,
      1.5,
      0.3
    ],
    [
      5,
      3,
      1.6,
      0.2
    ],
    [
      5.8,
      2.7,
      5.1,
      1.9
    ],
    [
      7.6,
      3,
      6.6,
      2.1
    ],
    [
      6.1,
      2.6,
      5.6,
      1.4
    ],
    [
      4.6,
      3.4,
      1.4,
      0.3
    ],
    [
      6,
      3,
      4.8,
      1.8
    ],
    [
      6.8,
      2.8,
      4.8,
      1.4
    ],
    [
      5.8,
      2.8,
      5.1,
      2.4
    ],
    [
      5.4,
      3.4,
      1.7,
      0.2
    ],
    [
      5.7,
      3.8,
      1.7,
      0.3
    ],
    [
      7.7,
      3.8,
      6.7,
      2.2
    ],
    [
      5.4,
      3.9,
      1.3,
      0.4
    ],
    [
      5,
      3.4,
      1.5,
      0.2
    ],
    [
      6.2,
      2.2,
      4.5,
      1.5
    ],
    [
      7.9,
      3.8,
      6.4,
      2
    ],
    [
      5.7,
      3,
      4.2,
      1.2
    ],
    [
      6.5,
      3.2,
      5.1,
      2
    ],
    [
      5.1,
      3.7,
      1.5,
      0.4
    ],
    [
      6.7,
      3.1,
      4.4,
      1.4
    ],
    [
      5.2,
      4.1,
      1.5,
      0.1
    ],
    [
      5.1,
      3.4,
      1.5,
      0.2
    ],
    [
      6.9,
      3.1,
      5.4,
      2.1
    ],
    [
      6.4,
      2.7,
      5.3,
      1.9
    ],
    [
      6,
      2.2,
      4,
      1
    ],
    [
      5,
      2,
      3.5,
      1
    ],
    [
      4.9,
      2.4,
      3.3,
      1
    ],
    [
      6.8,
      3.2,
      5.9,
      2.3
    ],
    [
      5.1,
      3.5,
      1.4,
      0.3
    ],
    [
      4.8,
      3.1,
      1.6,
      0.2
    ],
    [
      7.2,
      3.6,
      6.1,
      2.5
    ],
    [
      5.1,
      2.5,
      3,
      1.1
    ],
    [
      6.5,
      2.8,
      4.6,
      1.5
    ],
    [
      6,
      2.9,
      4.5,
      1.5
    ],
    [
      6.3,
      3.3,
      6,
      2.5
    ],
    [
      4.9,
      3.6,
      1.4,
      0.1
    ],
    [
      4.4,
      3.2,
      1.3,
      0.2
    ],
    [
      4.8,
      3.4,
      1.9,
      0.2
    ],
    [
      5.4,
      3.7,
      1.5,
      0.2
    ],
    [
      5.8,
      2.7,
      4.1,
      1
    ],
    [
      5.8,
      2.7,
      3.9,
      1.2
    ],
    [
      4.7,
      3.2,
      1.6,
      0.2
    ],
    [
      5.2,
      3.4,
      1.4,
      0.2
    ],
    [
      5.3,
      3.7,
      1.5,
      0.2
    ],
    [
      4.3,
      3,
      1.1,
      0.1
    ],
    [
      6.2,
      3.4,
      5.4,
      2.3
    ],
    [
      5,
      3.3,
      1.4,
      0.2
    ],
    [
      6.9,
      3.2,
      5.7,
      2.3
    ],
    [
      5,
      3.5,
      1.6,
      0.6
    ],
    [
      4.9,
      2.5,
      4.5,
      1.7
    ],
    [
      5.2,
      2.7,
      3.9,
      1.4
    ],
    [
      6,
      3.4,
      4.5,
      1.6
    ],
    [
      5.4,
      3,
      4.5,
      1.5
    ],
    [
      6.5,
      3,
      5.8,
      2.2
    ],
    [
      5.4,
      3.9,
      1.7,
      0.4
    ]
  ]
}"""

from mlflow.models import validate_serving_input
validate_serving_input(model_info.model_uri, serving_payload)

array([2, 2, 1, 2, 0, 0, 1, 0, 2, 0, 2, 0, 1, 1, 2, 0, 0, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 0, 1, 0, 1, 2, 0, 2, 0, 2, 2, 1,
       1, 2, 0, 2, 1, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 0,
       0, 2, 2, 2, 0, 2, 1, 2, 0, 0, 2, 0, 0, 1, 2, 1, 2, 0, 1, 0, 0, 2,
       2, 1, 1, 1, 2, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       2, 0, 2, 0, 2, 1, 1, 1, 2, 0])

<!-- #Load Model as Function -->

In [20]:
loaded_model = mlflow.pyfunc.load_model(model_info.model_uri)
predictions = loaded_model.predict(x_test)

iris_features_name = datasets.load_iris().feature_names
results = pd.DataFrame(x_test, columns=iris_features_name)
results["actual_class"] = y_test
results["predicted_class"] = predictions


In [21]:
results.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                6.4               3.2                4.5               1.5   
1                5.5               2.5                4.0               1.3   
2                7.0               3.2                4.7               1.4   
3                5.4               3.0                4.5               1.5   
4                5.0               3.2                1.2               0.2   

   actual_class  predicted_class  
0             1                1  
1             1                1  
2             1                1  
3             1                1  
4             0                0